version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      runtime:
        patterns:
          - "Microsoft.*"
          - "System.*"
      testing:
        patterns:
          - "coverlet.collector"
          - "FluentAssertions"
          - "NSubstitute"
          - "xunit*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
